language: python
matrix:
  include:
    - env:
        - PYTHON=3.6
        - STYLE_TEST=0
    - env:
        - PYTHON=3.6
        - STYLE_TEST=1
install:
    # install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    # install Python
    - conda create -q -n test-environment python=$PYTHON
    - source activate test-environment
    # install needed packages
    - if [ "${STYLE_TEST}" == "1" ]; then
          conda install -q pycodestyle;
      fi
    - conda list
    # install this package
    - python3 setup.py install
script:
    - if [ "${STYLE_TEST}" == "1" ]; then
          pycodestyle . --exclude=versioneer.py;
      fi

